#! /bin/bash
#
# Author: Edgar Zamora-Gómez, 2015
#
# /etc/init.d/bw_sender
#
### BEGIN INIT INFO
# Provides: bw_consumer
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: BW sender daemon process
# Description:
### END INIT INFO

case "$1" in
  start)
    echo "Starting sender"
    # Start the daemon
    python /home/vagrant/src/monitoring_app/bw_sender.py start
    ;;
  stop)
    echo "Stopping sender"
    # Stop the daemon
    python /home/vagrant/src/monitoring_app/bw_sender.py stop
    ;;
  restart)
    echo "Restarting sender"
    python /home/vagrant/src/monitoring_app/bw_sender.py restart
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/bw_sender.sh {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
